name: MBLeaderboardsAddon
version: 1.1.2
author: MetallicGoat
main: me.metallicgoat.bedwarsleaderboards.LeaderboardsPlugin
description: Adds leaderboards placeholders to MBedwars
api-version: 1.13
depend: [ MBedwars ]
softdepend: [ PlaceholderAPI ]