name: MBLeaderboardsAddon
version: 0.0.2
author: MetallicGoat
main: me.metallicgoat.bedwarsleaderboards.LeaderboardsPlugin
description: Adds leaderboards placeholders to MBedwars
api-version: 1.13
depend: [ MBedwars, PlaceholderAPI ]